### ISSUE TITLE
Missing the slides for "Christophe Pettus: PostgreSQL Proficiency for Python People"

### ISSUE THREAD

**Issue by felixhummel** [PyCon/2014-slides#1]
The [youtube description](http://www.youtube.com/watch?v=0uCxLCmzaG4) links to this Github repository, but it is empty.
Tom Øyvind Hogstad was kind enough to put a link to the slides in the comments: http://thebuild.com/presentations/pycon-2014-pppp.pdf
It would be great to see them mirrored here.

Cheers!

**Comment by mlhamel** [comment]
Hi Felix, thanks a ton, I've added those slides to the PyCon repos.

https://github.com/PyCon/2014-slides/blob/master/PostgreSQL%20Proficiency%20for%20Python%20People.pdf
